Add Contact List
Khikar-1997/Contact-Book pull request #2
Opened 2022-07-06 14:49 UTC by Khikar-1997

2022-07-06 15:14 UTC, griarman requested changes

2022-07-06 15:14 UTC, griarman commented on src/Screens/Components/ContactList/Avatar.js
> +import React from 'react';
please add case for users that hadn't images

2022-07-06 15:14 UTC, griarman commented on src/Screens/Components/ContactList/Avatar.js
> +          uri: contactList.item.avatar_image,
add question marks

2022-07-06 15:14 UTC, griarman commented on src/Screens/Components/ContactList/Avatar.js
> +    backgroundColor: '#1B2124',
please create COLORS file and add your colors there

2022-07-06 15:14 UTC, griarman commented on src/Screens/Components/ContactList/ContactInfo.js
> +const ContactInfo = ({ contactList }) => {
if in your component you don't write any logic, you don't need return

2022-07-06 15:14 UTC, griarman commented on src/Screens/Components/ContactList/ContactsList.js
> +    <View>
this is unnecessary View component

2022-07-06 15:14 UTC, griarman commented on src/Screens/Components/ContactList/ContactsList.js
> +          );
you can create component for this part

2022-07-06 17:55 UTC, griarman requested changes

2022-07-06 17:55 UTC, griarman commented on src/Components/ContactList/ContactInfo.js
> +      {surname ? `${name} ${surname}` : `${name}`}
`${name} ${surname || ''}`

2022-07-06 17:55 UTC, griarman commented on src/Screens/Contacts.screen.js
> +const Contacts = ({ navigation }) => (
you can use useNavigation hook

2022-07-06 17:55 UTC, griarman commented on src/UIKit/Avatar/index.js
> +          : `${name.charAt(0)}`}
please beautify this

2022-07-07 09:14 UTC, AnushavanGhulyan approved these changes

2022-07-07 09:14 UTC, merged