Feature/l5 c search in modal screen
Khikar-1997/Contact-Book pull request #5
Opened 2022-07-13 14:01 UTC by Khikar-1997

2022-07-15 16:16 UTC, AnushavanGhulyan requested changes

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Components/ContactList/FavoriteContactInfo.js
>    contactNameAndSurnameText: {
add "textAlign", and remove parent view

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Screens/Contacts.screen.js
> +
```suggestion
Contacts.options = ({ navigation }) => ({
headerRight: () => (
        <Button
          onPress={() => navigation.navigate(Routes.ADD_CONTACTS)}
          icon="add"
          size="small"
        />
      ),
  headerLeft: () => (
    <Avatar
      name="Khikar"
      surname="Harutyunyan"
      image={imagePaths.homePageAvatarImage}
      size="small"
    />
  ),
});

```

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Screens/Contacts.screen.js
> +  });
see below

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Screens/SearchContact.screen.js
> +      console.log('1');
remove console. log, and try without e.persist

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Screens/SearchContact.screen.js
> +    }, 2000);
decrease delay to 250ms

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Screens/SearchContact.screen.js
> +      ),
same here

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Screens/SearchContact.screen.js
> +    </View>
remove view

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/UIKit/Button/index.js
> +const Button = ({ onPress, icon, title = '', size, variant = '' }) => (
Add "default" variant,

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/UIKit/Button/index.js
> +import buttonColor from './variant';
Move these styles into this file, and merge it in one stylesheet object

2022-07-15 16:16 UTC, AnushavanGhulyan commented on src/Screens/SearchContact.screen.js
> +      setSearchedText(e.nativeEvent.text);
Move all logic here , filter data here, and passed filtered data to list

2022-07-17 23:29 UTC, griarman approved these changes

2022-07-18 14:21 UTC, merged