Feature/l6 c add contacts form
Khikar-1997/Contact-Book pull request #6
Opened 2022-07-21 13:06 UTC by Khikar-1997

2022-07-21 16:27 UTC, AnushavanGhulyan requested changes

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Actions/contacts.js
> +import { createAction } from '@reduxjs/toolkit/src/createAction';
please fix import path

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Actions/contacts.js
> +export const ADD_CONTACT = createAction('CONTACT/ADD_CONTACT');
make actions lowerCase

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Components/AddContacts/AddContact.js
> +        }),
remove Id generation from here.
do it inside reducer.

see example [https://redux-toolkit.js.org/api/createAction#using-prepare-callbacks-to-customize-action-contents](url),

use nanoId or your integrated uuid there

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Components/ContactList/FavoritesList.js
> +  const favoritesList = useMemo(() => filterFavorites(contacts), [contacts]);
create selector for filterFavorites based on getContacts. 
see example [https://redux-toolkit.js.org/api/createSelector](url)

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Components/ContactList/List.js
> +  const contactList = useMemo(() => contactListWithTitle(contacts), [contacts]);
same here

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Components/ContactSearch/SearchedContacts.js
> +  <View style={{ flex: 1 }}>
remove inline styles

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Config/store.js
> +export default createStore(contactsReducer);
change to configure store.

[https://redux-toolkit.js.org/tutorials/quick-start#create-a-redux-store](url)

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Reducers/contacts.js
> +};
```suggestion
const initialState = {
 contacts: MOCK_DATA,
};
```

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Screens/AddContact.screen.js
> +);
is this View is necessary?

2022-07-21 16:27 UTC, AnushavanGhulyan commented on src/Components/AddContacts/AddContact.js
> +import React, { useState } from 'react';
make attention to file names.

_src/Components/AddContacts/index.js_ is better name

2022-07-21 18:33 UTC, griarman requested changes

2022-07-21 18:33 UTC, griarman commented on src/Components/AddContacts/index.js
> +        placeholderTextColor={colors.logan}
please move this style into FiledForm

2022-07-21 18:33 UTC, griarman commented on src/Components/AddContacts/index.js
> +        placeholderTextColor={colors.logan}
same here

2022-07-21 18:33 UTC, griarman commented on src/Components/AddContacts/index.js
> +        placeholderTextColor={colors.logan}
same here

2022-07-21 18:33 UTC, griarman commented on src/Reducers/contacts.js
> +  contacts: contacts,
just write contacts

2022-07-21 18:33 UTC, griarman commented on src/Screens/AddContact.screen.js
> +const AddContactScreen = () => <AddContact />;
let instead of returning AddContact component move AddContact data into this screen

2022-07-22 08:51 UTC, AnushavanGhulyan requested changes

2022-07-22 08:51 UTC, AnushavanGhulyan commented on src/Actions/contacts.js
> +const id = uuidv4();
this will work only one time. so all new IDs will the same.
move Id creation inside action

2022-07-22 14:01 UTC, AnushavanGhulyan approved these changes

2022-07-25 16:35 UTC, AnushavanGhulyan approved these changes

2022-07-25 16:35 UTC, AnushavanGhulyan commented on src/Reducers/contacts.js
> +export const counterSlice = createSlice({
Please rename

2022-08-01 09:12 UTC, AnushavanGhulyan requested changes

2022-08-01 09:12 UTC, AnushavanGhulyan commented on src/Screens/SearchContact.screen.tsx
>  };
Let's declare this type global and use it for other screens also

2022-08-02 14:29 UTC, AnushavanGhulyan requested changes

2022-08-02 14:29 UTC, AnushavanGhulyan commented on src/Components/AddContacts/ImageUploadForm.tsx
> +  pickPicture: (event: GestureResponderEvent) => void;
wrong event type

2022-08-02 14:29 UTC, AnushavanGhulyan commented on src/Screens/AddContact.screen.tsx
> +  source: ImageURISource;
is this the right interface for this screen?

2022-08-02 15:33 UTC, AnushavanGhulyan approved these changes

2022-08-02 15:33 UTC, AnushavanGhulyan commented on src/Screens/AddContact.screen.tsx
> +          props={props}
remove props

2022-08-02 15:33 UTC, AnushavanGhulyan commented on src/Screens/AddContact.screen.tsx
> +          source={imagePaths.placeholderImage}
remove source

2022-08-02 15:33 UTC, AnushavanGhulyan commented on src/Components/AddContacts/ImageUploadForm.tsx
> +  uri: string;
remove uri props.
use source instead

2022-08-02 15:33 UTC, AnushavanGhulyan commented on src/Screens/AddContact.screen.tsx
> +          source={imagePaths.placeholderImage}
```suggestion
          source={uri ? { uri } :  imagePaths.placeholderImage}
```

2022-08-02 15:33 UTC, AnushavanGhulyan commented on src/Screens/AddContact.screen.tsx
> +const AddContactScreen = (props: AvatarProps) => {
remove "props"

2022-08-05 14:11 UTC, merged